### ISSUE TITLE
Don't access Crashlytics eagerly

### ISSUE THREAD

**Issue by mvysny** [mvysny/slf4j-handroid#5]
`HandroidLoggerAdapter` tries to eagerly detect the presence of Crashlytics in static initializer. However, it does so by calling `Class.forName("com.crashlytics.android.Crashlytics");` which tries to load the `Crashlytics` class. But if Multidex is not yet installed and Crashlytics is present in `classes-2.dex` that function will fail and Crashlytics will fail to initialize later on, with a very cryptic message:
```
04-14 19:12:08.411 3609-3609/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.crashlytics.android.answers.Answers
        at com.crashlytics.android.Crashlytics.<init>(Crashlytics.java:29)
        at sk.baka.photoframe.App.onCreate(App.java:97)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by mvysny** [comment]
The solution is to drop the eager initialization idea and add `HandroidLoggerAdapter.enableLoggingToCrashlytics()` which will do the initialization on-demand and is supposed to be called only after Multidex is properly installed and Crashlytics is properly initialized:

```
    @Override
    public void onCreate() {
        super.onCreate();
        Fabric.with(this, new Crashlytics());
        HandroidLoggerAdapter.enableLoggingToCrashlytics();
        ...
```
